name: Build and Deploy React App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Updated to Node.js 20 to match React Router requirements
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Update package-lock.json first to fix the sync issue
        npm install
        # Then install dependencies based on the updated lock file
        npm ci
      
    - name: Build React app
      run: npm run build
      env:
        CI: false  # This prevents the build from failing on warnings

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Deploy to VPS
      run: |
        scp -r -P ${{ secrets.SSH_PORT }} build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

    - name: Verify deployment
      run: |
        ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && ls -la"